"use client";

import { useEffect, useState } from "react";
import { Loader2, LogOut, Save } from "lucide-react";

import { Button } from "@/components/ui/Button";
import { FieldGroup, Input, Label, Select } from "@/components/ui/Field";
import { PrvNotice, PrvPanel } from "@/components/prv/PrvPanel";
import { usePrv } from "@/components/prv/usePrv";
import { formatDayName } from "@/lib/prv/weekly";

const DAYS = [0, 1, 2, 3, 4, 5, 6] as const;

/**
 * PRV · Paramètres privés.
 *
 * These thresholds drive the deterministic report, which is why they are stored server-side: a
 * report regenerated by the weekly cron must use exactly the same rules as the screen. The client
 * never sends a raw value through - the server clamps anything out of range.
 */
interface Settings {
  reportDay: number;
  moduleWeights: Record<string, number>;
  defaultModuleWeight: number;
  trendWindow: number;
  trendThreshold: number;
  onTrackRate: number;
  overdueWarningDays: number;
  aiEnabled: boolean;
}

const WEIGHTED_MODULES = ["M202", "M203", "M204"] as const;

export default function PrvSettingsPage() {
  const { busy, error, request, lock } = usePrv();
  const [settings, setSettings] = useState<Settings | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    request<Settings>("/api/prv/settings").then((payload) => {
      if (!cancelled && payload) setSettings(payload);
    });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const save = async () => {
    if (!settings) return;
    setSaveError(null);
    const result = await request<Settings>("/api/prv/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(settings),
    });
    if (result) {
      // The server clamps out-of-range values, so display what it actually stored.
      setSettings(result);
      setNotice("Paramètres enregistrés. Ils s'appliquent aux prochains rapports.");
    } else {
      setSaveError("Enregistrement impossible.");
    }
  };

  if (!settings) {
    return (
      <PrvPanel title="Paramètres privés">
        <p className="flex items-center gap-2 text-sm text-ink/50">
          <Loader2 className="h-4 w-4 animate-spin" /> Chargement…
        </p>
      </PrvPanel>
    );
  }

  return (
    <div className="space-y-5">
      {error && <PrvNotice tone="warn">{error}</PrvNotice>}
      {saveError && <PrvNotice tone="warn">{saveError}</PrvNotice>}
      {notice && <PrvNotice tone="good">{notice}</PrvNotice>}

      <PrvPanel
        title="Rapport hebdomadaire"
        subtitle="Le jour de fin de semaine détermine les dates de chaque rapport."
        action={
          <Button size="sm" onClick={() => void save()} disabled={busy}>
            {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Save className="h-3.5 w-3.5" />}
            Enregistrer
          </Button>
        }
      >
        <div className="grid gap-3 sm:grid-cols-2">
          <FieldGroup>
            <Label>Jour de clôture</Label>
            <Select
              value={settings.reportDay}
              onChange={(event) => setSettings({ ...settings, reportDay: Number(event.target.value) })}
            >
              {DAYS.map((day) => (
                <option key={day} value={day}>
                  {formatDayName(day)}
                </option>
              ))}
            </Select>
            <p className="mt-1 text-[11px] text-ink/45">
              La semaine se termine ce jour-là et dure toujours 7 jours.
            </p>
          </FieldGroup>
          <FieldGroup>
            <Label>Seuil « semaine tenue » (%)</Label>
            <Input
              type="number"
              min={0}
              max={100}
              value={settings.onTrackRate}
              onChange={(event) => setSettings({ ...settings, onTrackRate: Number(event.target.value) })}
            />
            <p className="mt-1 text-[11px] text-ink/45">
              Au-dessus de ce taux, la semaine reçoit une récompense dans le rapport.
            </p>
          </FieldGroup>
        </div>
      </PrvPanel>

      <PrvPanel title="Pondération des modules" subtitle="Coefficient × poids = poids réel du module dans la tendance.">
        <div className="grid gap-3 sm:grid-cols-2">
          <FieldGroup>
            <Label>Poids par défaut</Label>
            <Input
              type="number"
              min={0}
              max={2}
              step={0.05}
              value={settings.defaultModuleWeight}
              onChange={(event) => setSettings({ ...settings, defaultModuleWeight: Number(event.target.value) })}
            />
          </FieldGroup>
          {WEIGHTED_MODULES.map((moduleId) => (
            <FieldGroup key={moduleId}>
              <Label>Poids {moduleId}</Label>
              <Input
                type="number"
                min={0}
                max={2}
                step={0.05}
                value={settings.moduleWeights[moduleId] ?? settings.defaultModuleWeight}
                onChange={(event) =>
                  setSettings({
                    ...settings,
                    moduleWeights: { ...settings.moduleWeights, [moduleId]: Number(event.target.value) },
                  })
                }
              />
            </FieldGroup>
          ))}
        </div>
        <p className="mt-1 text-[11px] leading-relaxed text-ink/45">
          Ces trois modules valent 0,75 par défaut, c&apos;est-à-dire qu&apos;ils comptent moins que
          leur coefficient seul. Les valeurs hors de 0–2 sont refusées par le serveur.
        </p>
      </PrvPanel>

      <PrvPanel title="Tendance et retard" subtitle="Les règles qui produisent le verdict de tendance.">
        <div className="grid gap-3 sm:grid-cols-3">
          <FieldGroup>
            <Label>Fenêtre (semaines)</Label>
            <Input
              type="number"
              min={2}
              max={12}
              value={settings.trendWindow}
              onChange={(event) => setSettings({ ...settings, trendWindow: Number(event.target.value) })}
            />
          </FieldGroup>
          <FieldGroup>
            <Label>Seuil de variation (points)</Label>
            <Input
              type="number"
              min={0}
              max={100}
              value={settings.trendThreshold}
              onChange={(event) => setSettings({ ...settings, trendThreshold: Number(event.target.value) })}
            />
          </FieldGroup>
          <FieldGroup>
            <Label>Retard signalé après (jours)</Label>
            <Input
              type="number"
              min={1}
              max={90}
              value={settings.overdueWarningDays}
              onChange={(event) => setSettings({ ...settings, overdueWarningDays: Number(event.target.value) })}
            />
          </FieldGroup>
        </div>
      </PrvPanel>

      <PrvPanel title="Intelligence artificielle" subtitle="Désactiver l'IA n'efface aucun rapport déjà calculé.">
        <label className="flex items-center gap-2.5">
          <input
            type="checkbox"
            checked={settings.aiEnabled}
            onChange={(event) => setSettings({ ...settings, aiEnabled: event.target.checked })}
            className="h-4 w-4 rounded border-ink/20"
          />
          <span className="text-xs text-ink/75">Autoriser les propositions et l&apos;interprétation IA</span>
        </label>
        <p className="mt-2 text-[11px] leading-relaxed text-ink/45">
          Même activée, l&apos;IA ne propose qu&apos;elle : chaque tâche créée passe par votre
          confirmation, et aucun chiffre du rapport ne dépend du modèle.
        </p>
      </PrvPanel>

      <PrvPanel title="Session" subtitle="Verrouiller immédiatement sur cet appareil.">
        <Button size="sm" variant="danger" onClick={() => void lock()} disabled={busy}>
          <LogOut className="h-3.5 w-3.5" /> Verrouiller PRV
        </Button>
        <p className="mt-2 text-[11px] text-ink/45">
          Les rapports, PDF et notes « à revoir » restent stockés côté serveur et réapparaîtront à la
          prochaine ouverture.
        </p>
      </PrvPanel>
    </div>
  );
}
