/**
 * Persisted PRV settings (Paramètres privés).
 *
 * Stored server-side in the private file store, never in the browser, so a report regenerated by
 * the cron uses the same thresholds the owner configured in the UI.
 */

import "server-only";

import { readSingleton, writeSingleton } from "./store.server";
import { DEFAULT_SETTINGS, sanitizeSettings, type ReportSettings } from "./trajectory";

export function getSettings(): ReportSettings {
  return sanitizeSettings(readSingleton<ReportSettings>("settings", DEFAULT_SETTINGS));
}

export async function saveSettings(input: unknown): Promise<ReportSettings> {
  const next = sanitizeSettings(input, getSettings());
  await writeSingleton("settings", next);
  return next;
}
